# SPDX-License-Identifier: GPL-2.0+
include:
  - project: "tuxedocomputers/development/installation-testing/package-build-gitlab-ci-yaml"
    ref: "experimental"
    file: "includes/multi_distro.yml"
    inputs:
      spc_args: ""
      server_user: "deploy-deb-fixes"
      deploy_base_dir: "deb/tuxedo-fixes"
